# These descriptions are meant to be user-facing for each field
[CompareList_Field_Descriptions]
# prices are defined in the list in USD pennies, but should be displayed as a proper USD value (e.g. $5.00)
# for prices, -1 indicates free plan, -1 indicates that the given plan interval is not offered
price_monthly = "Monthly price for this plan in USD."
price_yearly =" Yearly price for this plan in USD."
price_lifetime = "If offered, lifetime price for this plan in USD."
included_bots = "Number of bots you can create with this plan."
components_per_bot = "Number of commands/events/etc. you can create per bot."
servers_per_bot = "Number of Discord servers a bot can be in."
flow_time_limit = "Time limit on user-created flows or code."
variable_storage = "Variable storage type offered."
database_storage = "Database storage type offered."
storage_limit = "Limits on storage."
music = "Are music features available?"
collaboration = "Develop bots with other users."
bot_status = "Customization options for bot status."
library = "Library system for sharing flows."
plugins = "Plugins or built-in modules."
flow_sharing = "Links or codes to share flows between bots."
support = "Official/priority support availability."
dashboard_themes = "Ability to set themes in the bot maker dashboard."
bot_dashboard = "System for creating bot dashboards."
notes = "Any additional details not covered by above."

[Inventor_Free]
price_monthly = -1
price_yearly = -1
price_lifetime = -1
included_bots = "3"
components_per_bot = "15 components"
servers_per_bot = 10
flow_time_limit = 10
variable_storage = true
database_storage = true
storage_limit = "500 Crates"
music = false
collaboration = true
bot_status = "invt.lol prefix"
library = true
plugins = "Soon"
flow_sharing = true
support = true
dashboard_themes = true
bot_dashboard = "BotDash (under construction)"

[Inventor_Premium]
price_monthly = 599
price_yearly = 4999
price_lifetime = -2
included_bots = "1"
components_per_bot = "Unlimited"
servers_per_bot = 1000
flow_time_limit = 30
variable_storage = true
database_storage = true
storage_limit = "20,000 Crates"
music = false
collaboration = true
bot_status = true
library = true
plugins = "Soon"
flow_sharing = true
support = true
dashboard_themes = true
bot_dashboard = "BotDash (under construction)"

[Inventor_Ultimate]
price_monthly = 1199
price_yearly = 9999
price_lifetime = -2
included_bots = "20"
components_per_bot = "Unlimited"
servers_per_bot = 1500
flow_time_limit = 45
variable_storage = true
database_storage = true
storage_limit = "30,000 Crates"
music = false
collaboration = true
bot_status = true
library = true
plugins = "Soon"
flow_sharing = true
support = true
dashboard_themes = true
bot_dashboard = "BotDash (under construction)"

[BotGhost_Free]
price_monthly = -1
price_yearly = -1
price_lifetime = -1
included_bots = "Unlimited"
components_per_bot = "3 commands, 3 events"
servers_per_bot = 5
flow_time_limit = "Unlimited"
variable_storage = true
database_storage = false
storage_limit = "Not specified"
music = false
collaboration = true
bot_status = "Listening to Made with BotGhost.com"
library = true
plugins = true
flow_sharing = true
support = false
dashboard_themes = false
bot_dashboard = "BotPanel (beta)"

[BotGhost_Premium_Single_Bot]
price_monthly = 1100
price_yearly = 4999
price_lifetime = 9999
included_bots = 1
components_per_bot = "Unlimited"
servers_per_bot = "Unlimited"
flow_time_limit = "Unlimited"
variable_storage = true
database_storage = false
storage_limit = "Not specified"
music = false
collaboration = true
bot_status = true
library = true
plugins = true
flow_sharing = true
support = true
dashboard_themes = false
bot_dashboard = "BotPanel (beta)"

[BotGhost_Premium_Multi_Bot]
price_monthly = 2399
price_yearly = 9999
price_lifetime = 14999
included_bots = "Unlimited"
components_per_bot = "Unlimited"
servers_per_bot = "Unlimited"
flow_time_limit = "Unlimited"
variable_storage = true
database_storage = false
storage_limit = "Not specified"
music = false
collaboration = true
bot_status = true
library = true
plugins = true
flow_sharing = true
support = true
dashboard_themes = false
bot_dashboard = "BotPanel (beta)"

[BotWiz_Free]
price_monthly = -1
price_yearly = -1
price_lifetime = -1
included_bots = "Unlimited"
components_per_bot = 10
servers_per_bot = "?"
flow_time_limit = "?"
variable_storage = true
database_storage = false
storage_limit = "Not specified"
music = false
collaboration = false
bot_status = "Watching Made with BotWiz.dev"
library = false
plugins = true
flow_sharing = true
support = true
dashboard_themes = true
bot_dashboard = false
notes = "A la carte pricing available"

[BotWiz_Basic]
price_monthly = 521
price_yearly = 7092
price_lifetime = 5840
included_bots = "1"
components_per_bot = "?"
servers_per_bot = "?"
flow_time_limit = "?"
variable_storage = true
database_storage = false
storage_limit = "Not specified"
music = false
collaboration = false
bot_status = true
library = false
plugins = true
flow_sharing = true
support = true
dashboard_themes = true
bot_dashboard = false
notes = "A la carte pricing available"

[BotWiz_Medium]
price_monthly = 939
price_yearly = 6383
price_lifetime = 10512
included_bots = "1"
components_per_bot = "?"
servers_per_bot = "?"
flow_time_limit = "?"
variable_storage = true
database_storage = false
storage_limit = "Not specified"
music = false
collaboration = false
bot_status = true
library = false
plugins = true
flow_sharing = true
support = true
dashboard_themes = true
bot_dashboard = false
notes = "A la carte pricing available"

[BotWiz_Wizards]
price_monthly = 1460
price_yearly = 9928
price_lifetime = 16353
included_bots = "1"
components_per_bot = "?"
servers_per_bot = "?"
flow_time_limit = "?"
variable_storage = true
database_storage = false
storage_limit = "Not specified"
music = true
collaboration = false
bot_status = true
library = false
plugins = true
flow_sharing = true
support = true
dashboard_themes = true
bot_dashboard = false
notes = "A la carte pricing available"
