# These descriptions are meant to be user-facing for each field
[CompareList_Field_Descriptions]
# prices are defined in the list in USD pennies, but should be displayed as a proper USD value (e.g. $5.00)
# for prices, -1 indicates free plan, -1 indicates that the given plan interval is not offered
price_monthly = "Monthly price for this plan in USD."
price_yearly =" Yearly price for this plan in USD."
price_lifetime = "If offered, lifetime price for this plan in USD."
bots_per_account = "Number of bots you can create."
components_per_bot = "Number of commands/events/etc. you can create per bot."
servers_per_bot = "Number of Discord servers a bot can be in."
flow_time_limit = "Time limit on user-created flows or code."
storage_type = "Type(s) of storage offered."
music = "Are music features available?"
collaboration = "Develop bots with other users."
bot_status = "Customization options for bot status."
prebuilt_commands = "Pre-made command and module availability."
support = "Official/priority support availability."
dashboard_themes = "Ability to set themes in the bot maker dashboard."
bot_dashboard = "System for creating bot dashboards."
notes = "Any additional details not covered by above."

[Inventor_Free]
price_monthly = -1
price_yearly = -1
price_lifetime = -1
bots_per_account = "3 free bots"
components_per_bot = "15 components (commands, events, or custom blocks)"
servers_per_bot = 10
flow_time_limit = 10
storage_type = "Global Variables"
storage_limit = "500 Crates"
music = false
collaboration = true
bot_status = "'Playing invt.lol' prefix"
prebuilt_commands = "Free, customizable, community-made library"
support = true
dashboard_themes = true
bot_dashboard = "BotDash (under construction)"

[Inventor_Premium]
price_monthly = 599
price_yearly = 4999
price_lifetime = -2
bots_per_account = " 1 premium, 3 free"
components_per_bot = "Unlimited"
servers_per_bot = 1000
flow_time_limit = 30
storage_type = "Global Variables and Databases"
storage_limit = "20,000 Crates"
music = false
collaboration = true
bot_status = true
prebuilt_commands = "Free, customizable, community-made library"
support = true
dashboard_themes = true
bot_dashboard = "BotDash (under construction)"

[Inventor_Ultimate]
price_monthly = 1199
price_yearly = 9999
price_lifetime = -2
bots_per_account = "20 premium, 3 free"
components_per_bot = "Unlimited"
servers_per_bot = 1500
flow_time_limit = 45
storage_type = "Global Variables and Databases"
storage_limit = "30,000 Crates"
music = false
collaboration = true
bot_status = true
prebuilt_commands = "Free, customizable, community-made library"
support = true
dashboard_themes = true
bot_dashboard = "BotDash (under construction)"

[BotGhost_Free]
price_monthly = -1
price_yearly = -1
price_lifetime = -1
bots_per_account = "Unlimited"
components_per_bot = "3 custom commands, 3 custom events"
servers_per_bot = 5
flow_time_limit = "Unlimited"
storage_type = "Variables"
storage_limit = "Not specified"
music = false
collaboration = true
bot_status = "Listening to Made with BotGhost.com"
prebuilt_commands = "Basic Modules"
support = false
dashboard_themes = false
bot_dashboard = "BotPanel (beta)"

[BotGhost_Premium]
price_monthly = 2399
price_yearly = 9999
price_lifetime = 14999
bots_per_account = "Unlimited"
components_per_bot = "Unlimited"
servers_per_bot = "Unlimited"
flow_time_limit = "Unlimited"
storage_type = "Variables"
storage_limit = "Not specified"
music = false
collaboration = true
bot_status = "Custom"
prebuilt_commands = "Premium Modules"
support = true
dashboard_themes = false
bot_dashboard = "BotPanel (beta)"

[BotWiz_Free]
price_monthly = -1
price_yearly = -1
price_lifetime = -1
bots_per_account = "Unknown"
components_per_bot = 10
servers_per_bot = "Unknown"
flow_time_limit = "Unknown"
storage_type = "Variables"
storage_limit = "Not specified"
music = false
collaboration = false
bot_status = "Watching Made with BotWiz.dev"
prebuilt_commands = "Modules"
support = true
dashboard_themes = true
bot_dashboard = "None"
notes = "A la carte pricing available"

[BotWiz_Basic]
price_monthly = 521
price_yearly = 7092
price_lifetime = 5840
bots_per_account = "Unlimited free? One premium"
components_per_bot = "?"
servers_per_bot = "?"
flow_time_limit = "?"
storage_type = "Global variables"
storage_limit = "Not specified"
music = false
collaboration = false
bot_status = true
prebuilt_commands = "Modules"
support = true
dashboard_themes = true
bot_dashboard = false
notes = "A la carte pricing available"

[BotWiz_Medium]
price_monthly = 939
price_yearly = 6383
price_lifetime = 10512
bots_per_account = "Unlimited free? One premium"
components_per_bot = "?"
servers_per_bot = "?"
flow_time_limit = "?"
storage_type = "Variables"
storage_limit = "Not specified"
music = false
collaboration = false
bot_status = true
prebuilt_commands = "Modules"
support = true
dashboard_themes = true
bot_dashboard = false
notes = "A la carte pricing available"

[BotWiz_Wizards]
price_monthly = 1460
price_yearly = 9928
price_lifetime = 16353
bots_per_account = "Unlimited free? One premium"
components_per_bot = "?"
servers_per_bot = "?"
flow_time_limit = "?"
storage_type = "Global variables"
storage_limit = "Not specified"
music = true
collaboration = "Offline collaboration (1 user at time)"
bot_status = true
prebuilt_commands = "Modules"
support = true
dashboard_themes = true
bot_dashboard = false
notes = "A la carte pricing available"
